### ISSUE TITLE
支付宝接口问题

### ISSUE THREAD

**Issue by BeiProject** [wxlost/ss-panel-v3-mod_UIChanges#1]
我的支付宝接口在配置文件都设置正确，但是我在网站进行充值的时候点击弹出在喝茶后无反应

**Comment by wxlost** [comment]
https://github.com/galaxychuck/ss-panel-v3-mod_UIChanges
请找原作者反馈下。这部分我没有动他。不清楚什么问题。我也用的支付没问题

**Comment by BeiProject** [comment]
大佬有联系方式吗，我想拜托你帮忙看一下原因

**Comment by BeiProject** [comment]
大佬有联系方式嘛
